# 기본 설정
spring:
  application:
    name: interest

---

# 기본 프로파일 (default)
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:interestdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        event-in:
          group: interest
          destination: output-topic   # 수정된 부분: 입력 채널의 토픽을 'output-topic'으로 변경
          contentType: application/json
        event-out:
          destination: input-topic    # 수정된 부분: 출력 채널의 토픽을 'input-topic'으로 변경
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

server:
  port: 8080

---

# 도커 프로파일 (docker)
spring:
  profiles: docker
  datasource:
    url: jdbc:h2:mem:interestdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
      bindings:
        event-in:
          group: interest
          destination: output-topic   # 수정된 부분: 입력 채널의 토픽을 'output-topic'으로 변경
          contentType: application/json
        event-out:
          destination: input-topic    # 수정된 부분: 출력 채널의 토픽을 'input-topic'으로 변경
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

server:
  port: 8083