apiVersion: apps/v1
kind: Deployment
metadata:
  name: interest
  labels:
    app: interest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interest
  template:
    metadata:
      labels:
        app: interest
    spec:
      containers:
        - name: interest
          image: "yeseong33/interest:241010"
          ports:
            - containerPort: 8080
