apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesmanmatch
  labels:
    app: salesmanmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesmanmatch
  template:
    metadata:
      labels:
        app: salesmanmatch
    spec:
      containers:
        - name: salesmanmatch
          image: "yeseong33/salesmanmatch:241010"
          ports:
            - containerPort: 8080
