apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesmanmatch
  labels:
    app: salesmanmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesmanmatch
  template:
    metadata:
      labels:
        app: salesmanmatch
    spec:
      containers:
        - name: salesmanmatch
          image: "username/salesmanmatch:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
