---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interest
  labels:
    app: interest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interest
  template:
    metadata:
      labels:
        app: interest
    spec:
      containers:
        - name: interest
          image: jhemj/interest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultation
  labels:
    app: consultation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultation
  template:
    metadata:
      labels:
        app: consultation
    spec:
      containers:
        - name: consultation
          image: jhemj/consultation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: jhemj/project:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesmanmatch
  labels:
    app: salesmanmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesmanmatch
  template:
    metadata:
      labels:
        app: salesmanmatch
    spec:
      containers:
        - name: salesmanmatch
          image: jhemj/salesmanmatch:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: jhemj/gateway:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: interest
  labels:
    app: interest
spec:
  type: ClusterIP  # ClusterIP으로 변경
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: interest

---

apiVersion: v1
kind: Service
metadata:
  name: consultation
  labels:
    app: consultation
spec:
  type: ClusterIP  # ClusterIP으로 변경
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: consultation

---

apiVersion: v1
kind: Service
metadata:
  name: project
  labels:
    app: project
spec:
  type: ClusterIP  # ClusterIP으로 변경
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: project

---

apiVersion: v1
kind: Service
metadata:
  name: salesmanmatch
  labels:
    app: salesmanmatch
spec:
  type: ClusterIP  # ClusterIP으로 변경
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: salesmanmatch

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer  # Gateway만 LoadBalancer로 유지
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway